<?php

namespace Iyuu\Spider\Sysop;

use Iyuu\Spider\Contract\Route;
use Iyuu\Spider\Exceptions\DownloadTorrentException;
use Iyuu\Spider\Sites\Sites;
use think\Collection;

/**
 * 支持所有站点
 */
class AnySite extends Sites
{
    /**
     * 必须实现
     * - 返回种子元数据
     * @param null $args
     * @return string|bool|null
     * @throws DownloadTorrentException
     */
    public function download($args = null): string|bool|null
    {
        throw new DownloadTorrentException('TODO: Change the autogenerated stub');
    }

    /**
     * 不需要
     * @return Collection
     */
    public function process(): Collection
    {
        // TODO: Implement process() method.
    }

    /**
     * 不需要
     * @param int $page
     * @param Route|string|null $route
     * @return string
     */
    public static function pageBuilder(int $page, Route|string $route = null): string
    {
        // TODO: Implement pageBuilder() method.
    }

    /**
     * 不需要
     * @return int
     */
    public function nextPage(): int
    {
        // TODO: Implement nextPage() method.
    }

    /**
     * 不需要
     * @return int
     */
    public function currentPage(): int
    {
        // TODO: Implement currentPage() method.
    }
}
